run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: false
        description: "Run ID"
        type: string

jobs:
  upsert:
    runs-on: ubuntu-latest
    steps:
      - name: Create entity
        uses: port-labs/port-github-action@c6b6f19dcdcb091be6ed788f9bc3b84f69620643
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          blueprint: 'test'
          identifier: '${{ inputs.run_id }}-entity'
          runId: ${{ inputs.run_id }}
